/**
 * Copyright 2016–2020 Duolingo
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * ...
 */

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

String VERSION = '2.0.0'

apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'

repositories {
    google()
    mavenCentral()
}

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 29
    }
}

dependencies {
    compileOnly 'androidx.viewpager:viewpager:1.0.0'
}

group = 'com.github.Artur-Abalov'
version = VERSION
